spring:
 main:
  allow-bean-definition-overriding: true
  allow-circular-references: true
 application:
  name: product-pricing
 datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}   
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 100000
      max-lifetime: 1800000
server:
  port: 8080
  servlet:
    context-path: /product-pricing
    
logging:
  level:
    ROOT: INFO